version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1

jobs:
  security-scans:
    docker:
      - image: cimg/go:1.19.4
    resource_class: small
    steps:
      - checkout
      - prodsec/security_scans:
          mode: auto

workflows:
  version: 2
  CICD:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: group-infrastructure-as-code-alerts
      - security-scans:
          name: Security Scans
          context:
            - analysis-iac
