# !Make sure the secret scanning workflow is the first one in the pipeline
# to ensure leaked secrets are detected before any other operation
name: Snyk Detect Secrets

on: [push, pull_request]

jobs:
  secrets-scan:
    uses: snyk/prodsec-orb/.github/workflows/secrets-scanning.yml@main
    with:
      channel: group-infrastructure-as-code-alerts
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

