name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test with Go ${{ matrix.go }}
    strategy:
      matrix:
        go: ["1.19", "1.20"]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - run: go test ./...

  # Snyk jobs
  #
  # Rotate the SNYK_TOKEN in
  # https://app.snyk.io/org/cloud-cloud/manage/service-accounts if needed, and
  # replace it in the GitHub repository secrets. The service account is named
  # cli-extension-iac-rules-ci.
  snyk-oss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=medium --org=cloud-cloud

  snyk-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code
          args: test --severity-threshold=medium --org=cloud-cloud
