name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test with Go ${{ matrix.go }}
    strategy:
      matrix:
        go: ["1.18", "1.19", "1.20"]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - run: go test ./...
